apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager
  labels:
    app: taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: tarun08code/taskmanager:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: taskmanager-service
spec:
  selector:
    app: taskmanager
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30007